# Generated by Django 2.2 on 2020-12-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalaxyOffset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='prod_color',
            field=models.CharField(max_length=50, verbose_name='Product Color'),
        ),
    ]
