# Generated by Django 2.0.5 on 2020-09-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GalaxyOffset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aqutouscoatingproductmap',
            table='Aqutous Coating Product Mapping',
        ),
    ]
