# Generated by Django 2.2 on 2020-12-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalaxyOffset', '0002_auto_20201205_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noofmonths',
            name='months',
            field=models.CharField(max_length=15, verbose_name='No of Months'),
        ),
    ]
