# Generated by Django 2.2 on 2020-12-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalaxyOffset', '0003_auto_20201205_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.ImageField(default=500, max_length=10, upload_to='', verbose_name='Product Quantity'),
        ),
    ]
