# Generated by Django 2.0.5 on 2020-09-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GalaxyOffset', '0003_auto_20200930_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AqutousCoatingProductMap',
            new_name='AqutousCoatingProductMapping',
        ),
        migrations.RenameModel(
            old_name='BindingMethodProductMap',
            new_name='BindingMethodProductMapping',
        ),
        migrations.RenameModel(
            old_name='ColorProductMap',
            new_name='ColorProductMapping',
        ),
        migrations.RenameModel(
            old_name='FoldingOptionsProductMap',
            new_name='FoldingOptionsProductMapping',
        ),
        migrations.RenameModel(
            old_name='HoleDrillingProductMap',
            new_name='HoleDrillingProductMapping',
        ),
        migrations.RenameModel(
            old_name='ImageTemplateProductMap',
            new_name='ImageTemplateProductMapping',
        ),
        migrations.RenameModel(
            old_name='NoOfMonthsProductMap',
            new_name='NoOfMonthsProductMapping',
        ),
        migrations.RenameModel(
            old_name='PaperChoiceProductMap',
            new_name='PaperChoiceProductMapping',
        ),
        migrations.RenameModel(
            old_name='ShrinkWrappingProductMap',
            new_name='ShrinkWrappingProductMapping',
        ),
        migrations.RenameModel(
            old_name='SizeProductMap',
            new_name='SizeProductMapping',
        ),
    ]
