# Generated by Django 2.0.5 on 2020-09-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GalaxyOffset', '0004_auto_20200930_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
