# Generated by Django 2.2 on 2020-12-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GalaxyOffset', '0004_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindingmethodproductmapping',
            name='binding_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GalaxyOffset.BindingMethod', verbose_name='Binding Methods ID'),
        ),
    ]
