# Generated by Django 2.0.5 on 2020-10-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalaxyOffset', '0005_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Product Image'),
        ),
    ]
