# Generated by Django 2.0.5 on 2020-10-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalaxyOffset', '0006_product_prod_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=8, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Designer', 'Designer'), ('Customer', 'Customer')], default='Customer', max_length=10, verbose_name='User Type'),
        ),
    ]
