# Generated by Django 2.0.5 on 2020-10-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalaxyOffset', '0007_auto_20201004_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallary',
            name='img_name',
        ),
        migrations.AddField(
            model_name='gallary',
            name='img_path',
            field=models.ImageField(default='', upload_to='', verbose_name='Image Path'),
        ),
    ]
